export const styles = {
  container: {
    backgroundColor: "#f4f7f9",
    minHeight: "100vh",
    padding: "var(--container-padding, 20px)",
    fontFamily: "Inter, sans-serif",
  },
  header: {
    maxWidth: "1200px",
    margin: "0 auto 20px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "var(--header-align, center)",
    flexDirection: "var(--header-direction, row)",
    flexWrap: "var(--header-wrap, nowrap)",
    gap: "var(--header-gap, 0px)",
  },
  userButton: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    cursor: "pointer",
    backgroundColor: "#fff",
    padding: "8px 16px",
    borderRadius: "10px",
    border: "1px solid #e2e8f0",
    boxShadow: "0 1px 2px rgba(0,0,0,0.05)",
  },
  userName: { fontSize: "0.9rem", color: "#334155", fontWeight: "600" },
  arrow: { fontSize: "0.7rem", color: "#64748b" },
  dropdown: {
    position: "absolute",
    top: "100%",
    right: 0,
    marginTop: "8px",
    backgroundColor: "#fff",
    border: "1px solid #e2e8f0",
    borderRadius: "8px",
    boxShadow: "0 4px 6px rgba(0,0,0,0.1)",
    zIndex: 10,
  },
  logoutBtn: {
    padding: "10px 15px",
    border: "none",
    background: "none",
    color: "#ef4444",
    fontSize: "0.85rem",
    cursor: "pointer",
    fontWeight: "500",
    width: "100%",
    textAlign: "left",
  },
  loginBtn: {
    padding: "8px 16px",
    borderRadius: "8px",
    border: "1px solid #004a99",
    background: "#fff",
    color: "#004a99",
    cursor: "pointer",
    fontWeight: "600",
  },
  dashboardAdmin: {
    maxWidth: "1200px",
    margin: "0 auto",
    display: "grid",
    gridTemplateColumns: "var(--dashboard-columns, 1fr 2fr)",
    gap: "var(--dashboard-gap, 30px)",
  },
  dashboardPublic: { maxWidth: "800px", margin: "0 auto" },
  card: {
    background: "#fff",
    padding: "var(--card-padding, 25px)",
    borderRadius: "15px",
    boxShadow: "0 4px 10px rgba(0,0,0,0.05)",
  },
  cardTitle: {
    fontSize: "1.2rem",
    fontWeight: "bold",
    marginBottom: "20px",
    borderBottom: "2px solid #f3f4f6",
    paddingBottom: "10px",
  },
  detailsSummary: {
    fontSize: "1.2rem",
    fontWeight: "bold",
    paddingBottom: "10px",
    cursor: "pointer",
  },
  detailsContent: { marginTop: "20px" },
  formFlex: {
    display: "grid",
    gridTemplateColumns: "var(--form-columns, 1fr 1fr)",
    gap: "var(--form-gap, 15px)",
  },
  inputGroup: { display: "flex", flexDirection: "column" },
  label: {
    fontSize: "0.8rem",
    fontWeight: "bold",
    marginBottom: "4px",
    color: "#4b5563",
  },
  input: { padding: "10px", borderRadius: "8px", border: "1px solid #d1d5db" },
  selector: {
    width: "100%",
    padding: "10px 12px",
    borderRadius: "8px",
    border: "1px solid #e2e8f0",
    fontSize: "0.95rem",
    outline: "none",
    boxSizing: "border-box",
    backgroundColor: "#fff",
    color: "#1e293b",

    // Añadimos estas líneas para la flecha personalizada
    appearance: "none", // Elimina la flecha nativa (Chrome, Safari, Firefox)
    WebkitAppearance: "none",
    MozAppearance: "none",

    // Dibujamos una flecha simple con SVG como imagen de fondo
    backgroundImage: `url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="%2364748b" viewBox="0 0 16 16"><path d="M7.247 11.14 2.451 5.658C1.885 5.013 2.345 4 3.204 4h9.592a1 1 0 0 1 .753 1.659l-4.796 5.48a1 1 0 0 1-1.506 0z"/></svg>')`,
    backgroundRepeat: "no-repeat",
    backgroundPosition: "calc(100% - 15px) center", // AQUÍ AJUSTAS LA POSICIÓN: 15px desde la derecha
    backgroundSize: "12px",
  },
  submitBtn: {
    gridColumn: "1/-1",
    padding: "14px",
    background: "#004a99",
    color: "#fff",
    border: "none",
    borderRadius: "8px",
    fontWeight: "bold",
    cursor: "pointer",
  },
  statsNav: {
    display: "flex",
    gap: "var(--stats-nav-gap, 20px)",
    flexWrap: "var(--stats-nav-wrap, nowrap)",
    marginBottom: "15px",
    borderBottom: "1px solid #e2e8f0",
    paddingBottom: "10px",
  },
  statNavLink: {
    background: "none",
    border: "none",
    fontSize: "0.85rem",
    fontWeight: "700",
    cursor: "pointer",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    paddingBottom: "10px",
  },
  chartCard: {
    background: "#fff",
    padding: "25px",
    borderRadius: "15px",
    border: "1px solid #e2e8f0",
  },
  statsSummaryGrid: {
    display: "grid",
    gridTemplateColumns: "var(--summary-columns, 1fr 1fr 1fr)",
    gap: "var(--summary-gap, 15px)",
    marginTop: "25px",
    borderTop: "1px solid #f1f5f9",
    paddingTop: "20px",
  },
  statSummaryItem: { textAlign: "center" },
  statSummaryLabel: {
    fontSize: "0.7rem",
    color: "#94a3b8",
    fontWeight: "800",
    letterSpacing: "0.05em",
    display: "block",
  },
  statSummaryValue: { fontSize: "1.4rem", color: "#1e293b", fontWeight: "800" },
  historyList: {
    display: "grid",
    /* auto-fit: ajusta las columnas automáticamente.
       minmax(300px, 1fr): cada tarjeta mide mínimo 300px. 
       Si no caben dos de 300px, el navegador pone solo una.
    */
    gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))",
    gap: "20px",
    width: "100%",
    padding: "0",
    boxSizing: "border-box",
  },
  historyCard: {
    background: "#fff",
    padding: "20px",
    borderRadius: "16px",
    border: "1px solid #e2e8f0",
    width: "100%", // Ocupa todo el ancho de su columna en el grid
    maxWidth: "none", // Eliminamos cualquier restricción previa
    boxSizing: "border-box",
  },
  historyHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "15px",
  },
  dateBadge: {
    fontSize: "0.75rem",
    fontWeight: "700",
    color: "#000000",
    backgroundColor: "#f1f5f9",
    padding: "4px 12px",
    borderRadius: "20px",
    display: "inline-block",
    WebkitPrintColorAdjust: "exact",
    printColorAdjust: "exact",
  },
  historyGrid: {
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "space-between",
    textAlign: "center",
  },
  dataBlock: { display: "flex", flexDirection: "column", padding: "8px" },
  dataLabel: {
    fontSize: "0.65rem",
    color: "#9ca3af",
    textTransform: "uppercase",
  },
  dataValue: { fontSize: "1.1rem", color: "#1e293b", fontWeight: "700" },
  unit: {
    fontSize: "0.7rem",
    color: "#94a3b8",
    fontWeight: "400",
    marginLeft: "2px",
  },
  notaBox: {
    marginTop: "15px",
    padding: "12px",
    background: "#f8fafc",
    borderRadius: "10px",
    fontSize: "0.85rem",
    fontStyle: "italic",
    borderLeft: "4px solid #004a99",
    color: "#475569",
  },
  deleteBtn: {
    color: "#ef4444",
    border: "none",
    background: "none",
    cursor: "pointer",
    fontWeight: "bold",
    fontSize: "0.75rem",
  },
  modalOverlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
    padding: "20px",
  },
  modalContent: {
    backgroundColor: "#ffffff",
    borderRadius: "16px",
    padding: "24px",
    width: "90%",
    maxWidth: "500px",
    position: "relative",
    zIndex: 1000,

    // --- AÑADE ESTAS LÍNEAS ---
    maxHeight: "90vh", // No permite que el modal ocupe más del 90% de la altura de la pantalla
    overflowY: "auto", // Habilita el scroll interno si el contenido es muy largo
    display: "flex",
    flexDirection: "column",
  },
  modalTitle: {
    fontSize: "1.2rem",
    fontWeight: "700",
    color: "#1e293b",
    marginBottom: "10px",
  },
  modalText: {
    fontSize: "0.95rem",
    color: "#64748b",
    marginBottom: "20px",
    lineHeight: "1.5",
  },
  modalButtons: {
    display: "flex",
    gap: "12px",
    justifyContent: "center",
  },
  btnFiltro: {
    padding: "6px 14px",
    borderRadius: "20px",
    fontSize: "0.65rem",
    fontWeight: "700",
    cursor: "pointer",
    border: "1px solid #e2e8f0",
    textTransform: "uppercase",
    transition: "all 0.2s",
    backgroundColor: "#fff",
    color: "#64748b",
  },
  // Colores para estados activos
  btnFiltroActivo: { backgroundColor: "#004a99", color: "#fff" },
  btnAM: { backgroundColor: "#f59e0b", color: "#fff" },
  btnPM: { backgroundColor: "#7c3aed", color: "#fff" },
  btnCancelar: {
    padding: "10px 20px",
    borderRadius: "8px",
    border: "1px solid #e2e8f0",
    background: "#f8fafc",
    color: "#64748b",
    cursor: "pointer",
    fontWeight: "600",
    fontSize: "0.9rem",
    transition: "all 0.2s",
  },
  selectorFiltro: {
    fontSize: "0.85rem",
    padding: "8px 12px",
    width: "auto",
    cursor: "pointer",
  },
};
